### ISSUE TITLE
ML.Net 1 - RegressaoLinear.ipynb Novos Exemplos 

### ISSUE THREAD

**Issue by claubercy** [DaviRamos/DadosAoCubo#1]
Olá Davi.

Estou começando no mundo de ML.

Usando esse seu exemplo ao plotar o gráfico está dando os seguintes erros:

1) Primeiro não reconhecia o "using XPlot.Plotly". Então adicionei o #r "nuget:XPlot.Plotly" e passou desse erro.

2) Agora está dando o erro ao plotar o gráfico:

Error: (12,24): error CS0246: The type or namespace name 'Graph' could not be found (are you missing a using directive or an assembly reference?)

Se você puder me ajudar eu agradeço

**Comment by claubercy** [comment]
Atualizei a célula que Plota o gráfico Scatter e funcionou. O único porém é que abriu uma página html e não ficou embutido no jupyter notebook e/ou Visual Studio Code:

// Exemplo de um Gráfico do tipo Scatter com o XPlot

var hx = new List<float>();
var hf = new List<float>();

foreach (var item in houseData)
{
   hx.Add(item.Size);
   hf.Add(item.Price);    
}

var tx = new List<float>();
var tf = new List<float>();

foreach (var item in testHouseData)
{
   tx.Add(item.Size);
   tf.Add(item.Price);    
}

var chart_list = new List<Scatter> 
{
    new Scatter
    {
        x = hx, 
        y = hf,
        name = "Dados de Treinamento",
        mode = "lines"
    },
    new Scatter
    {
        name = "Dados de Teste",
        x = tx, 
        y = tf,
        mode = "lines"
    }
};

var chart = Chart.Plot(
        chart_list
);

var chart_layout = new Layout.Layout{
        title="Treinamento vs Teste",
        xaxis =new Xaxis{
            title = "Size"
            },
        yaxis =new Yaxis{
        title = "Price"
            }           
        };
chart.WithLayout(chart_layout);
chart.Show();

**Comment by DaviRamos** [comment]
Olá claubercy como vai tudo bem contigo ?

Então me perode a demora.

O trbalho me consumiu muito estes dias

Vc estava correto na dientificação do erro

O que fiz para resolver o problema foi adicionar a linha abaixo no caderno porque ela estava faltando na chamada dos pacotes do nuget

Aqui nos mesus teste isso resolveu
//  XPlot
#r "nuget:XPlot.Plotly,2.0.0"
